# Generated by Django 4.1.7 on 2023-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0002_clasedeprueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='fechaentrega',
        ),
    ]
