# Generated by Django 4.1.7 on 2023-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0004_alter_evaluacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nCom1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nCom2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nCom3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nComR1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nComR2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nComR3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='totalCom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='totalObj',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
