# Generated by Django 4.1.7 on 2023-05-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0008_alter_evaluacion_comv1_alter_evaluacion_comv2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estado', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.TextField(choices=[('OPERATIVO', 'OBJETIVO OPERATIVO'), ('ADMINISTRATIVO', 'OBJETIVO ADMINISTRATIVO'), ('ESTRATEGICO', 'OBJETIVO ESTRATEGICO')])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ClasedePrueba',
        ),
        migrations.AddField(
            model_name='objetivos',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.periodo'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.objetivos'),
        ),
    ]
