# Generated by Django 4.1.7 on 2023-06-06 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0009_actividades_objetivos_periodo_delete_clasedeprueba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(default=0)),
                ('valor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('resultado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comentarios', models.TextField(default='')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.evaluaciondesempeno')),
                ('objetivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.objetivos')),
            ],
        ),
        migrations.DeleteModel(
            name='DetallesEvaluacion',
        ),
    ]
