# Generated by Django 4.1.7 on 2023-06-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0010_evaluaciondesempeno_evaluacionobjetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.objetivos'),
        ),
    ]
