# Generated by Django 4.1.7 on 2023-06-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0011_alter_evaluacionobjetivo_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.actividades')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.evaluacionobjetivo')),
            ],
        ),
    ]
