# Generated by Django 4.1.7 on 2023-06-13 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0014_evaluaciondesempeno_resultadocompetencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Autoevaluacion'), (1, 'Evaluacion')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
