# Generated by Django 4.1.7 on 2023-06-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0015_evaluaciondesempeno_estado_evaluaciondesempeno_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='niveles',
            name='nivel',
        ),
        migrations.CreateModel(
            name='EvaluacionCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.evaluaciondesempeno')),
            ],
        ),
    ]
