# Generated by Django 4.1.7 on 2023-06-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0016_nivel_remove_niveles_nivel_evaluacioncompetencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveles',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='performanceGC.nivel'),
        ),
        migrations.AlterField(
            model_name='competencias',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.nivel'),
        ),
    ]
