# Generated by Django 4.1.7 on 2023-06-14 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0017_niveles_nivel_alter_competencias_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresCompetencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('significado', models.TextField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.competencias')),
            ],
        ),
    ]
