# Generated by Django 4.1.7 on 2023-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0019_evaluacioncompetencia_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='pesoCompetencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluacioncompetencia',
            name='resultadoCompetencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
