# Generated by Django 4.1.7 on 2023-06-21 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0020_evaluacioncompetencia_pesocompetencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncompetencia',
            name='pesoCompetencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
