# Generated by Django 4.1.7 on 2023-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0022_alter_evaluacioncompetencia_pesocompetencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionCompetencia1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionCompetencia2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionCompetencia3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionTecConductual1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionTecConductual2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeno',
            name='deteccionTecConductual3',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
