# Generated by Django 4.1.7 on 2023-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0024_alter_direccion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ficha',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
