# Generated by Django 4.1.7 on 2023-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0026_alter_evaluaciondesempeno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionobjetivo',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
