# Generated by Django 4.1.7 on 2023-08-02 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0028_competencias_significado1_competencias_significado2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencias',
            name='valor1',
        ),
        migrations.RemoveField(
            model_name='competencias',
            name='valor2',
        ),
        migrations.RemoveField(
            model_name='competencias',
            name='valor3',
        ),
        migrations.RemoveField(
            model_name='competencias',
            name='valor4',
        ),
        migrations.AlterField(
            model_name='evaluacioncompetencia',
            name='pesoCompetencia',
            field=models.PositiveIntegerField(default=1, help_text='Ingrese un valor entre 1 y 4.', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='evaluacionobjetivo',
            name='peso',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evaluacionobjetivo',
            name='valor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
