# Generated by Django 4.1.7 on 2023-08-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0029_remove_competencias_valor1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='fechaFinEvaluaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fechaInicioEvaluaciones',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
