# Generated by Django 4.1.7 on 2023-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0030_periodo_fechafinevaluaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='evaluacionesHabilitadas',
            field=models.BooleanField(default=False),
        ),
    ]
