# Generated by Django 4.1.7 on 2023-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0033_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='hora',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
