# Generated by Django 4.1.7 on 2023-10-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0034_remove_comentarios_hora_alter_comentarios_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.departamento')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.niveles')),
            ],
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='tipo',
            field=models.TextField(default='Objetivo de Area'),
        ),
        migrations.CreateModel(
            name='DistribucionObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Objetivo de Area', max_length=200)),
                ('peso', models.IntegerField(default=0)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.distribucion')),
            ],
        ),
        migrations.AddField(
            model_name='gerencia',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceGC.departamento'),
        ),
    ]
