# Generated by Django 4.1.7 on 2023-10-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0036_alter_objetivos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas_Frecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='año',
        ),
        migrations.AddField(
            model_name='periodo',
            name='año_fin',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='periodo',
            name='año_inicio',
            field=models.IntegerField(default=2023),
        ),
    ]
