# Generated by Django 4.1.7 on 2023-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0037_preguntas_frecuentes_remove_periodo_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='año_fin',
            field=models.IntegerField(default=2024, unique=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='año_inicio',
            field=models.IntegerField(default=2023, unique=True),
        ),
    ]
