# Generated by Django 4.2.6 on 2023-10-30 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0041_cargo_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion_PNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Factores_de_evaluacion_PNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('enfoque', models.CharField(choices=[('Buenas practicas operativas', 'Buenas Practicas Operativas'), ('Procesos', 'Procesos'), ('Seguridad y salud laboral', 'Seguridad y Salud Laboral'), ('Competencias actidudinales', 'Competencias Actitudinales')], default='Buenas practicas operativas', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='niveles',
            name='formato_de_evaluacion',
            field=models.TextField(choices=[('pns', 'Personal de Nomina Semanal'), ('pnm', 'Personal de Nomina Mensual')], default='pnm'),
        ),
        migrations.CreateModel(
            name='Evaluacion_PNS_BPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.evaluacion_pns')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.factores_de_evaluacion_pns')),
            ],
        ),
    ]
