# Generated by Django 4.2.6 on 2023-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0042_evaluacion_pns_factores_de_evaluacion_pns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_evaluado',
            field=models.BooleanField(default=True),
        ),
    ]
