# Generated by Django 4.2.6 on 2023-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0043_empleado_es_evaluado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='nombre_infocent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
