# Generated by Django 4.2.6 on 2024-01-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0045_announcements_periodo_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performanceGC.objetivos')),
            ],
        ),
    ]
