# Generated by Django 4.2.6 on 2024-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceGC', '0046_objectives_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
