# Generated by Django 4.2.6 on 2024-02-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performanceGC', '0048_objectives_notes_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'ordering': ['created'], 'verbose_name': 'Objetivo Especifico', 'verbose_name_plural': 'Objetivos Especificos'},
        ),
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nivel', 'nombreText'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-fecha'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='company_objectives',
            options={'verbose_name': 'Objetivo de la Empresa', 'verbose_name_plural': 'Objetivos de la Empresa'},
        ),
        migrations.AlterModelOptions(
            name='competencias',
            options={'ordering': ['nivel', 'nombre'], 'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['id'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='distribucion',
            options={'ordering': ['departamento'], 'verbose_name': 'Distribución de Objetivos', 'verbose_name_plural': 'Distribuciones de Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='distribucionobjetivo',
            options={'ordering': ['tipo'], 'verbose_name': 'Distribución de Objetivo por nivel', 'verbose_name_plural': 'Distribuciones de Objetivos por niveles'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['ficha'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion_pns',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evaluación PNS', 'verbose_name_plural': 'Evaluaciones PNS'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion_pns_bpo',
            options={'ordering': ['factor'], 'verbose_name': 'Evaluación BPO', 'verbose_name_plural': 'Evaluaciones BPO'},
        ),
        migrations.AlterModelOptions(
            name='evaluacioncompetencia',
            options={'ordering': ['competencia'], 'verbose_name': 'Evaluación de Competencia', 'verbose_name_plural': 'Evaluaciones de Competencias'},
        ),
        migrations.AlterModelOptions(
            name='evaluaciondesempeno',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evaluación de Desempeño', 'verbose_name_plural': 'Evaluaciones de Desempeño'},
        ),
        migrations.AlterModelOptions(
            name='evaluacionobjetivo',
            options={'ordering': ['objetivo'], 'verbose_name': 'Evaluación de Objetivo', 'verbose_name_plural': 'Evaluaciones de Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='factores_de_evaluacion_pns',
            options={'ordering': ['enfoque', 'nombre'], 'verbose_name': 'Factor de Evaluación PNS', 'verbose_name_plural': 'Factores de Evaluación PNS'},
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'ordering': ['id'], 'verbose_name': 'Gerencia', 'verbose_name_plural': 'Gerencias'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['nivel'], 'verbose_name': 'Clasificación de Nivel', 'verbose_name_plural': 'Clasificación de Niveles'},
        ),
        migrations.AlterModelOptions(
            name='niveles',
            options={'ordering': ['valor'], 'verbose_name': 'Nivel de Cargo', 'verbose_name_plural': 'Niveles de Cargos'},
        ),
        migrations.AlterModelOptions(
            name='objectives_notes',
            options={'ordering': ['created_at'], 'verbose_name': 'Nota de Objetivo', 'verbose_name_plural': 'Notas de Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='objetivoactividad',
            options={'ordering': ['actividad'], 'verbose_name': 'Peso Objetivo Especifico', 'verbose_name_plural': 'Pesos Objetivos Especificos'},
        ),
        migrations.AlterModelOptions(
            name='objetivos',
            options={'ordering': ['created'], 'verbose_name': 'Objetivo General', 'verbose_name_plural': 'Objetivos Generales'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-año_inicio'], 'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.AlterModelOptions(
            name='preguntas_frecuentes',
            options={'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.AddField(
            model_name='objetivos',
            name='aproved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetivos',
            name='is_aproved',
            field=models.BooleanField(default=False),
        ),
    ]
