# Generated by Django 4.2.6 on 2024-02-14 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performanceGC', '0049_alter_actividades_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmpleado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True)),
                ('nombre', models.TextField(max_length=200)),
                ('apellido', models.TextField(max_length=200)),
                ('cedula', models.IntegerField(db_index=True, default=0)),
                ('ficha', models.IntegerField(db_index=True, default=0)),
                ('ceco', models.CharField(max_length=15)),
                ('fechaIngreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fechaEgreso', models.DateField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('es_evaluado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='performanceGC.cargo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empleado',
                'verbose_name_plural': 'historical Empleados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
